project: 
  type: website
  output-dir: docs
  resources:
    - figures

website:
  title: "Genomic Data Carpentry (Aotearoa edition)"
  favicon: theme-images/GA-image-black-favicon.png
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  sidebar:
    style: "docked"
    left:
    contents:
      - text: "_test styles"
        href: test-styling.qmd
      - text: "_outtakes/notes"
        href: outtakes-notes.qmd
      - text: "Home"
        href: index.qmd
      - text: "Organisation and tidy data"
        href: organisation-tidiness.qmd
      - text: "Planning for submission"
        href: planning-for-submission.qmd
      - text: "Genomic data storage and management"
        href: data-storage-and-management.qmd
      - text: "Genomic data wrangling and processing"
        href: data-wrangling-and-processing.qmd

    
    tools:
      - icon: github
        text: Github
        href: https://github.com/GenomicsAotearoa/genomic-data-carpentry-nz


format:
  html:
    include-before-body: banner.html
    code-tools: false
    code-block-bg: true
    code-block-title: true
    code-overflow: wrap
    page-layout: full
    toc: true
    toc-depth: 4
    css: styles.css
    navigation: true
    page-navigation: true

